using System.Text;
using MultiSeat.Shared;
using MultiSeat.Shared.Models;

namespace MultiSeat.Service.Streaming;

/// <summary>
/// Generates per-seat Apollo/Sunshine configuration files.
///
/// Each seat gets a unique sunshine.conf with:
///   - Unique server name (for Moonlight client identification)
///   - Isolated port range (HTTPS, HTTP, Video, Audio, Control)
///   - Display output target (SudoVDA device path)
///   - Audio sink (VAC cable device ID)
///   - Encoder preferences (NVENC → AMF → software)
///   - Controller and input settings
///   - Logging paths
///
/// Apollo/Sunshine config format is key=value pairs (INI-like).
/// Documentation: https://docs.lizardbyte.dev/projects/sunshine/
///
/// The config file is written to:
///   {configDir}/{seatId:N}/sunshine.conf
/// </summary>
public sealed class ApolloConfigBuilder
{
    private readonly ILogger<ApolloConfigBuilder> _logger;

    public ApolloConfigBuilder(ILogger<ApolloConfigBuilder> logger)
    {
        _logger = logger;
    }

    /// <summary>
    /// Generate a per-seat sunshine.conf and write it to the Apollo config directory.
    /// Returns the absolute path to the generated config file.
    /// </summary>
    public string BuildConfig(SeatInfo seat, string configDir)
    {
        var seatDir = Path.Combine(configDir, seat.Id.ToString("N"));
        Directory.CreateDirectory(seatDir);

        var configPath = Path.Combine(seatDir, "sunshine.conf");
        var logPath = Path.Combine(seatDir, "apollo.log").Replace('\\', '/');
        // All seats share one credentials file so web UI login persists across re-provisioning.
        // The file is created by MultiSeat on first run (from Apollo's default config) and survives seat teardown.
        var credPath = Path.Combine(configDir, "shared_credentials.json").Replace('\\', '/');
        EnsureSharedCredentials(configDir);
        // Pre-create per-seat state file so Apollo uses a unique server UUID per instance.
        // If the file doesn't exist when Apollo starts, it falls back to the shared default at
        // C:\Program Files\Apollo\config\sunshine_state.json — all seats would share one UUID
        // and Moonlight would deduplicate them, showing only one server.
        // Only create if absent so pairings survive re-provisioning.
        EnsureSeatStateFile(seatDir);

        var sb = new StringBuilder(2048);

        // ── Header ────────────────────────────────────────────────────
        sb.AppendLine($"# Auto-generated by MultiSeat for seat {seat.Id}");
        sb.AppendLine($"# Account: {seat.AccountName}");
        sb.AppendLine($"# Generated: {DateTimeOffset.UtcNow:O}");
        sb.AppendLine($"# Do not edit — changes will be overwritten on next seat provision.");
        sb.AppendLine();

        // ── Server identity ───────────────────────────────────────────
        // Each seat has a unique name visible in Moonlight's server list.
        // Include a seat number derived from the port block so multiple seats
        // with the same account are distinguishable (e.g. MultiSeat-RogAlly-1).
        var seatNumber = (seat.PortBase - Constants.PortBase) / Constants.PortsPerSeat + 1;
        sb.AppendLine("# Server identity");
        sb.AppendLine($"sunshine_name = MultiSeat-{seat.AccountName}-{seatNumber}");
        sb.AppendLine();

        // ── Network ports ─────────────────────────────────────────────
        // Apollo uses 'port' as the HTTPS base; other ports are derived:
        //   HTTPS = port + 0  (pairing + web UI)
        //   HTTP  = port + 1  (web UI http fallback)
        //   Video = port + 2  (RTP video stream)
        //   Audio = port + 3  (RTP audio stream)
        //   Control = port + 4 (ENet control channel)
        sb.AppendLine("# Network — unique port range for this seat");
        sb.AppendLine($"port = {seat.PortBase + Constants.OffsetHttps}");
        sb.AppendLine();

        // ── Display ───────────────────────────────────────────────────
        // always_use_virtual_display: Apollo creates and manages its own SudoVDA
        // virtual monitor per instance. Each running Apollo holds a device handle
        // to the SudoVDA adapter; Windows presents that monitor as active only
        // while the handle is open. No external display assignment is needed.
        sb.AppendLine("# Display — Apollo creates and owns a SudoVDA virtual display per instance");
        sb.AppendLine("always_use_virtual_display = enabled");
        sb.AppendLine($"resolutions = [{seat.Width}x{seat.Height}]");
        // Provide all standard framerates up to the seat's configured max so Moonlight
        // can offer the user a choice. Apollo picks the closest supported rate.
        var allFps = new[] { 30, 60, 90, 120, 144, 160, 240 };
        var fpsList = string.Join(", ", allFps.Where(f => f <= seat.Fps));
        sb.AppendLine($"fps = [{fpsList}]");
        sb.AppendLine();

        // ── Encoder ───────────────────────────────────────────────────
        // Prefer NVENC for hardware-accelerated low-latency encoding.
        // Apollo will fall back to AMF → software if NVENC is unavailable.
        sb.AppendLine("# Encoder — NVENC for hardware-accelerated low-latency encoding");
        sb.AppendLine("encoder = nvenc");
        sb.AppendLine();

        // ── Audio output (game audio → Moonlight) ─────────────────────
        // Leave audio_sink empty — Apollo uses the session's default render endpoint.
        // In an RDP session with default audiomode (redirect to client), that endpoint is
        // "Remote Audio Output", which IS enumerable via WASAPI and supports loopback capture.
        // VAC/VoiceMeeter devices are NOT visible in RDP sessions via WASAPI loopback capture,
        // so specifying them causes Apollo to fail silently (no audio in Moonlight).
        sb.AppendLine("# Audio output — Apollo captures session default (Remote Audio Output in RDP session)");
        sb.AppendLine("# audio_sink = (intentionally empty — use session default)");
        sb.AppendLine();

        // ── Audio input (mic from Moonlight → game) ────────────────────
        // virtual_sink: Apollo receives mic audio from the Moonlight client and renders it
        // to this device. Games then use the corresponding capture endpoint as their microphone.
        // VB-Audio CABLE: Apollo renders TO "CABLE Input", games record FROM "CABLE Output".
        // Note: this uses WASAPI render (not loopback capture), so VB-Cable IS accessible
        // in RDP sessions — different API path from the audio_sink loopback limitation.
        // Enable mic capture in Moonlight client settings for this to take effect.
        if (!string.IsNullOrEmpty(seat.AudioDeviceId))
        {
            sb.AppendLine("# Audio input — Apollo plays Moonlight mic audio to VB-Cable; games mic = CABLE Output");
            sb.AppendLine($"virtual_sink = {seat.AudioDeviceId}");
        }
        else
        {
            sb.AppendLine("# virtual_sink = (no VAC device assigned — mic forwarding unavailable)");
        }
        sb.AppendLine();

        // ── Input ─────────────────────────────────────────────────────
        // ViGEm virtual controllers are auto-detected by Apollo
        sb.AppendLine("# Input — ViGEm virtual controllers are auto-detected");
        sb.AppendLine("controller = enabled");
        sb.AppendLine("gamepad = auto");
        sb.AppendLine("# Moonlight sends KBM input; Apollo creates virtual KBM in-session");
        sb.AppendLine("keybindings_enabled = enabled");
        sb.AppendLine("mouse = enabled");
        sb.AppendLine("keyboard = enabled");
        sb.AppendLine();

        // ── Security ──────────────────────────────────────────────────
        // Each seat gets its own state file so Apollo generates a unique uniqueid per seat.
        // Without this, all instances load sunshine_state.json from the Apollo install dir
        // and share the same uniqueid — Moonlight deduplicates by uniqueid and shows only one server.
        var statePath = Path.Combine(seatDir, "sunshine_state.json").Replace('\\', '/');
        sb.AppendLine("# Security");
        sb.AppendLine($"sunshine_state = {statePath}");
        sb.AppendLine($"credentials_file = {credPath}");
        // Each seat has independent pairing — Moonlight pairs per-seat
        sb.AppendLine("origin_web_ui_allowed = lan");
        sb.AppendLine();

        // ── Streaming quality ─────────────────────────────────────────
        sb.AppendLine("# Streaming quality");
        sb.AppendLine("min_threads = 2");
        sb.AppendLine("hevc_mode = 2");  // allow HEVC if client supports it
        sb.AppendLine("av1_mode = 2");   // allow AV1 if client supports it — with encoder=software, AV1 probe just warns and continues (harmless)
        sb.AppendLine("fec_percentage = 20");
        sb.AppendLine();

        // ── Color settings ────────────────────────────────────────────
        // color_space = 1 → Rec. 709 (correct for HD content; default 0 = Rec. 601 SD)
        // color_range = 1 → full range (0–255); default 0 = limited range (16–235), which
        //   crushes blacks/whites and makes text look washed out / blurry on PC monitors.
        // For sharpest text, also enable "4:4:4 color mode" in Moonlight's Advanced settings
        // on the client — that negotiates YUV 4:4:4 instead of 4:2:0 chroma subsampling.
        sb.AppendLine("# Color — Rec. 709 full-range for sharp text on PC monitors");
        sb.AppendLine("color_space = 1");
        sb.AppendLine("color_range = 1");
        sb.AppendLine();

        // ── Logging ───────────────────────────────────────────────────
        sb.AppendLine("# Logging");
        sb.AppendLine("min_log_level = info");
        sb.AppendLine($"log_path = {logPath}");
        sb.AppendLine();

        // ── Advanced ──────────────────────────────────────────────────
        sb.AppendLine("# Advanced — notify MultiSeat on client connect/disconnect");
        // Apollo can call external commands on client events
        // We could use this to transition seat state Streaming ↔ Ready
        sb.AppendLine("# ping_timeout = 10000");
        sb.AppendLine("# back_button_timeout = 2000");

        File.WriteAllText(configPath, sb.ToString(), Encoding.UTF8);
        _logger.LogDebug("Wrote Apollo config to {Path} ({Bytes} bytes)",
            configPath, sb.Length);

        return configPath;
    }

    /// <summary>
    /// Update an existing config file with new audio device ID.
    /// Called after VAC cable assignment, which happens after initial config generation.
    /// </summary>
    public void UpdateAudioSink(string configPath, string audioDeviceId)
    {
        if (!File.Exists(configPath))
        {
            _logger.LogWarning("Config file not found for audio update: {Path}", configPath);
            return;
        }

        var lines = File.ReadAllLines(configPath);
        var updated = false;

        for (int i = 0; i < lines.Length; i++)
        {
            if (lines[i].StartsWith("audio_sink = ") ||
                lines[i].StartsWith("# audio_sink = "))
            {
                lines[i] = $"audio_sink = {audioDeviceId}";
                updated = true;
                break;
            }
        }

        if (updated)
        {
            File.WriteAllLines(configPath, lines, Encoding.UTF8);
            _logger.LogDebug("Updated audio_sink in {Path}", configPath);
        }
    }

    /// <summary>
    /// Update an existing config file with the virtual display device path.
    /// Called after SudoVDA creation.
    /// </summary>
    public void UpdateDisplayOutput(string configPath, string displayDevicePath)
    {
        if (!File.Exists(configPath))
        {
            _logger.LogWarning("Config file not found for display update: {Path}", configPath);
            return;
        }

        var lines = File.ReadAllLines(configPath);
        var updated = false;

        for (int i = 0; i < lines.Length; i++)
        {
            if (lines[i].StartsWith("output_name = ") ||
                lines[i].StartsWith("# output_name = "))
            {
                lines[i] = $"output_name = {displayDevicePath}";
                updated = true;
                break;
            }
        }

        if (updated)
        {
            File.WriteAllLines(configPath, lines, Encoding.UTF8);
            _logger.LogDebug("Updated output_name in {Path}", configPath);
        }
    }

    /// <summary>
    /// Ensure a per-seat sunshine_state.json exists with a unique server UUID.
    /// Only creates the file if absent — preserves pairings on re-provision.
    /// </summary>
    private void EnsureSeatStateFile(string seatDir)
    {
        var statePath = Path.Combine(seatDir, "sunshine_state.json");
        if (File.Exists(statePath)) return;

        // UUID format matches what Apollo writes: uppercase 8-4-4-4-12
        var uuid = Guid.NewGuid().ToString("D").ToUpperInvariant();
        var json = $$"""
            {
                "root": {
                    "named_devices": [],
                    "uniqueid": "{{uuid}}"
                }
            }
            """;

        File.WriteAllText(statePath, json, Encoding.UTF8);
        _logger.LogInformation("Created per-seat state file with UUID {Uuid}: {Path}", uuid, statePath);
    }

    /// <summary>
    /// Ensure the shared credentials file exists in the Apollo config root.
    /// If it doesn't exist yet, seed it from Apollo's default install location
    /// so the user doesn't have to set up credentials again from scratch.
    /// Apollo reads this file lazily on each web-UI/pairing request.
    /// </summary>
    private void EnsureSharedCredentials(string configDir)
    {
        var sharedCred = Path.Combine(configDir, "shared_credentials.json");
        if (File.Exists(sharedCred)) return;

        // Try to seed from Apollo's default credentials location
        var apolloDefault = @"C:\Program Files\Apollo\config\credentials.json";
        if (File.Exists(apolloDefault))
        {
            try
            {
                File.Copy(apolloDefault, sharedCred);
                _logger.LogInformation("Seeded shared credentials from Apollo default: {Path}", apolloDefault);
                return;
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Could not seed credentials from Apollo default");
            }
        }

        // Create a placeholder — user must visit the Apollo web UI (https://localhost:PORT) to set credentials
        _logger.LogWarning(
            "No shared credentials found at {Path}. " +
            "Visit the Apollo web UI after provisioning a seat to create credentials, " +
            "then the file will persist for future seats.",
            sharedCred);
    }

    /// <summary>
    /// Delete the config directory for a seat (on teardown).
    /// </summary>
    public void CleanupConfig(Guid seatId, string configDir)
    {
        var seatDir = Path.Combine(configDir, seatId.ToString("N"));
        if (Directory.Exists(seatDir))
        {
            try
            {
                Directory.Delete(seatDir, recursive: true);
                _logger.LogDebug("Cleaned up Apollo config dir: {Path}", seatDir);
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex,
                    "Failed to clean up Apollo config dir: {Path}", seatDir);
            }
        }
    }
}
