using System.Diagnostics;
using System.Text;
using Microsoft.Extensions.Options;
using MultiSeat.Service.Configuration;
using MultiSeat.Shared;
using MultiSeat.Shared.Models;

namespace MultiSeat.Service.Streaming;

/// <summary>
/// Generates per-seat Apollo/Sunshine configuration files.
///
/// Each seat gets a unique sunshine.conf with:
///   - Unique server name (for Moonlight client identification)
///   - Isolated port range (HTTPS, HTTP, Video, Audio, Control)
///   - Display output target (SudoVDA device path)
///   - Audio sink (VAC cable device ID)
///   - Encoder preferences (NVENC → AMF → software)
///   - Controller and input settings
///   - Logging paths
///
/// Apollo/Sunshine config format is key=value pairs (INI-like).
/// Documentation: https://docs.lizardbyte.dev/projects/sunshine/
///
/// The config file is written to:
///   {configDir}/{seatId:N}/sunshine.conf
/// </summary>
public sealed class ApolloConfigBuilder
{
    private readonly ILogger<ApolloConfigBuilder> _logger;
    private readonly MultiSeatOptions _options;

    public ApolloConfigBuilder(ILogger<ApolloConfigBuilder> logger, IOptions<MultiSeatOptions> options)
    {
        _logger = logger;
        _options = options.Value;
    }

    /// <summary>
    /// Generate a per-seat sunshine.conf and write it to the Apollo config directory.
    /// Returns the absolute path to the generated config file.
    /// </summary>
    public string BuildConfig(SeatInfo seat, string configDir)
    {
        var seatDir = Path.Combine(configDir, seat.Id.ToString("N"));
        Directory.CreateDirectory(seatDir);

        var configPath = Path.Combine(seatDir, "sunshine.conf");
        var logPath = Path.Combine(seatDir, "apollo.log").Replace('\\', '/');
        var statePath = Path.Combine(seatDir, "config", "sunshine_state.json").Replace('\\', '/');
        // All seats share one credentials file so web UI login persists across re-provisioning.
        // The file is created by MultiSeat on first run (from Apollo's default config) and survives seat teardown.
        var credPath = Path.Combine(configDir, "shared_credentials.json").Replace('\\', '/');
        EnsureSharedCredentials(configDir);
        // platf::appdata() on Windows resolves to {exe_dir}/config/ — not the working directory.
        // To isolate each seat's state file (and thus its UUID), we seed sunshine_state.json in
        // the per-seat config/ dir and write an explicit file_state = <absolute_path> in the
        // generated sunshine.conf so Apollo uses that path instead of the shared exe-dir default.
        // Only create if absent — pairings (stored in sunshine_state) survive re-provisioning.
        EnsureSeatConfigDir(seatDir);
        EnsureSeatStateFile(seatDir);
        EnsureSeatAppsJson(seatDir);

        var sb = new StringBuilder(2048);

        // ── Header ────────────────────────────────────────────────────
        sb.AppendLine($"# Auto-generated by MultiSeat for seat {seat.Id}");
        sb.AppendLine($"# Account: {seat.AccountName}");
        sb.AppendLine($"# Generated: {DateTimeOffset.UtcNow:O}");
        sb.AppendLine($"# Do not edit — changes will be overwritten on next seat provision.");
        sb.AppendLine();

        // ── Server identity ───────────────────────────────────────────
        // Each seat has a unique name visible in Moonlight's server list.
        // Include a seat number derived from the port block so multiple seats
        // with the same account are distinguishable (e.g. MultiSeat-RogAlly-1).
        var seatNumber = (seat.PortBase - Constants.PortBase) / Constants.PortsPerSeat + 1;
        sb.AppendLine("# Server identity");
        sb.AppendLine($"sunshine_name = MultiSeat-{seat.AccountName}-{seatNumber}");
        sb.AppendLine();

        // ── Network ports ─────────────────────────────────────────────
        // Apollo uses 'port' as the HTTPS base; other ports are derived:
        //   HTTPS = port + 0  (pairing + web UI)
        //   HTTP  = port + 1  (web UI http fallback)
        //   Video = port + 2  (RTP video stream)
        //   Audio = port + 3  (RTP audio stream)
        //   Control = port + 4 (ENet control channel)
        sb.AppendLine("# Network — unique port range for this seat");
        sb.AppendLine($"port = {seat.PortBase + Constants.OffsetHttps}");
        sb.AppendLine();

        // ── Display ───────────────────────────────────────────────────
        // output_name is set after SudoVDA creates the virtual display (UpdateDisplayOutput).
        // always_use_virtual_display is NOT a sunshine.conf key in ClassicOldSong/Apollo — it
        // was moved to per-paired-device state in sunshine_state.json. MultiSeat manages the
        // virtual display externally via VirtualDisplayManager; output_name points Apollo at it.
        sb.AppendLine("# Display — output_name set to SudoVDA virtual display UUID");
        if (!string.IsNullOrEmpty(seat.DisplayDevicePath))
            sb.AppendLine($"output_name = {seat.DisplayDevicePath}");
        else
            sb.AppendLine("# output_name = pending");
        sb.AppendLine($"resolutions = [{seat.Width}x{seat.Height}]");
        // Provide all standard framerates up to the seat's configured max so Moonlight
        // can offer the user a choice. Apollo picks the closest supported rate.
        var allFps = new[] { 30, 60, 90, 120, 144, 160, 240 };
        var fpsList = string.Join(", ", allFps.Where(f => f <= seat.Fps));
        sb.AppendLine($"fps = [{fpsList}]");
        sb.AppendLine();

        // ── Encoder ───────────────────────────────────────────────────
        // Prefer NVENC for hardware-accelerated low-latency encoding.
        // Apollo will fall back to AMF → software if NVENC is unavailable.
        sb.AppendLine("# Encoder — NVENC for hardware-accelerated low-latency encoding");
        sb.AppendLine("encoder = nvenc");
        sb.AppendLine();

        // ── NVENC tuning ──────────────────────────────────────────────
        var (nvencPresetNum, nvencTwopass, nvencSpatialAq, nvencVbvIncrease) =
            GetNvencSettings(seat.NvencPreset);
        sb.AppendLine($"# NVENC tuning — {seat.NvencPreset} preset");
        sb.AppendLine($"nvenc_preset = {nvencPresetNum}");
        sb.AppendLine($"nvenc_twopass = {nvencTwopass}");
        sb.AppendLine($"nvenc_spatial_aq = {nvencSpatialAq}");
        sb.AppendLine($"nvenc_vbv_increase = {nvencVbvIncrease}");
        sb.AppendLine("nvenc_latency_over_power = enabled");
        sb.AppendLine();

        // ── Audio output (game audio → Moonlight) ─────────────────────
        // audio_sink: Apollo WASAPI loopback-captures from this render device to stream game
        // audio to Moonlight. Requires audiomode:i:1 in the RDP session (set in Default.rdp)
        // so host audio devices (VB-CABLE, VoiceMeeter) are visible via WASAPI inside the
        // RDP session. SeatManager sets this device as the session's default render so games
        // automatically output to it without any manual device selection.
        if (!string.IsNullOrEmpty(seat.AudioGameRenderFriendlyName))
        {
            sb.AppendLine("# Audio output — Apollo loopback-captures session default render for game audio");
            sb.AppendLine($"audio_sink = {seat.AudioGameRenderFriendlyName}");
        }
        else
        {
            sb.AppendLine("# audio_sink = (no game audio device assigned)");
        }
        sb.AppendLine();

        // ── Audio input (mic from Moonlight → game) ────────────────────
        // stream_mic: Apollo receives Moonlight mic audio, decodes Opus frames, and renders
        // them into "Speakers (Steam Streaming Microphone)". SeatManager sets
        // "Microphone (Steam Streaming Microphone)" as the session default capture so games
        // automatically use it. Requires Steam installed for its audio driver.
        // Client must be logabell/moonlight-qt-mic (standard Moonlight does not send mic packets).
        sb.AppendLine("# Audio input — Apollo streams Moonlight mic into Steam Streaming Microphone");
        sb.AppendLine("stream_mic = enabled");
        sb.AppendLine();

        // ── Input ─────────────────────────────────────────────────────
        // ViGEm virtual controllers are auto-detected by Apollo
        sb.AppendLine("# Input — ViGEm virtual controllers are auto-detected");
        sb.AppendLine("controller = enabled");
        sb.AppendLine("gamepad = auto");
        sb.AppendLine("# Moonlight sends KBM input; Apollo creates virtual KBM in-session");
        sb.AppendLine("keybindings_enabled = enabled");
        sb.AppendLine("mouse = enabled");
        sb.AppendLine("keyboard = enabled");
        sb.AppendLine();

        // ── Security ──────────────────────────────────────────────────
        // file_state must be an absolute path — Apollo resolves relative paths against
        // {exe_dir}/config/, which is shared by all instances. Each seat needs its own
        // sunshine_state.json so Moonlight sees distinct UUIDs and lists them separately.
        sb.AppendLine("# Security");
        sb.AppendLine($"file_state = {statePath}");
        sb.AppendLine($"credentials_file = {credPath}");
        // Each seat has independent pairing — Moonlight pairs per-seat
        sb.AppendLine("origin_web_ui_allowed = lan");
        sb.AppendLine();

        // ── Streaming quality ─────────────────────────────────────────
        sb.AppendLine("# Streaming quality");
        sb.AppendLine("min_threads = 2");
        sb.AppendLine("hevc_mode = 2");  // allow HEVC if client supports it
        sb.AppendLine("av1_mode = 2");   // allow AV1 if client supports it — with encoder=software, AV1 probe just warns and continues (harmless)
        sb.AppendLine("fec_percentage = 20");
        sb.AppendLine();

        // ── Color settings ────────────────────────────────────────────
        // color_space = 1 → Rec. 709 (correct for HD content; default 0 = Rec. 601 SD)
        // color_range = 1 → full range (0–255); default 0 = limited range (16–235), which
        //   crushes blacks/whites and makes text look washed out / blurry on PC monitors.
        // For sharpest text, also enable "4:4:4 color mode" in Moonlight's Advanced settings
        // on the client — that negotiates YUV 4:4:4 instead of 4:2:0 chroma subsampling.
        sb.AppendLine("# Color — Rec. 709 full-range for sharp text on PC monitors");
        sb.AppendLine("color_space = 1");
        sb.AppendLine("color_range = 1");
        sb.AppendLine();

        // ── Logging ───────────────────────────────────────────────────
        sb.AppendLine("# Logging");
        sb.AppendLine("min_log_level = info");
        sb.AppendLine($"log_path = {logPath}");
        sb.AppendLine();

        // ── Advanced ──────────────────────────────────────────────────
        sb.AppendLine("# Advanced — notify MultiSeat on client connect/disconnect");
        // Apollo can call external commands on client events
        // We could use this to transition seat state Streaming ↔ Ready
        sb.AppendLine("# ping_timeout = 10000");
        sb.AppendLine("# back_button_timeout = 2000");

        File.WriteAllText(configPath, sb.ToString(), Encoding.UTF8);
        _logger.LogDebug("Wrote Apollo config to {Path} ({Bytes} bytes)",
            configPath, sb.Length);

        return configPath;
    }

    /// <summary>
    /// Update an existing config file with the virtual display device path.
    /// Called after SudoVDA creation.
    /// </summary>
    public void UpdateDisplayOutput(string configPath, string displayDevicePath)
    {
        if (!File.Exists(configPath))
        {
            _logger.LogWarning("Config file not found for display update: {Path}", configPath);
            return;
        }

        var lines = File.ReadAllLines(configPath);
        var updated = false;

        for (int i = 0; i < lines.Length; i++)
        {
            if (lines[i].StartsWith("output_name = ") ||
                lines[i].StartsWith("# output_name = "))
            {
                lines[i] = $"output_name = {displayDevicePath}";
                updated = true;
                break;
            }
        }

        if (updated)
        {
            File.WriteAllLines(configPath, lines, Encoding.UTF8);
            _logger.LogInformation("Updated output_name={DevicePath} in {Path}", displayDevicePath, configPath);
        }
    }

    /// <summary>
    /// Ensure the per-seat config/ and config/credentials/ subdirectories exist,
    /// and seed the TLS cert/key from Apollo's install dir.
    ///
    /// Apollo resolves config files from {exe_dir}/config/ by default.
    /// We override file_state and credentials_file to absolute per-seat paths in the conf:
    ///   sunshine_state.json — unique UUID per seat (Moonlight server identity)
    ///   apps.json           — game/app list (no override; always copied fresh each provision)
    ///   credentials/        — TLS cert + key for HTTPS pairing
    ///
    /// ProcessInjector sets workingDir = seatDir. BUILTIN\Users only has Write
    /// (create files), not Modify (create subdirectories), on ProgramData dirs.
    /// Pre-creating these dirs as SYSTEM avoids Apollo exiting on credentials mkdir failure.
    /// </summary>
    private void EnsureSeatConfigDir(string seatDir)
    {
        var configDir = Path.Combine(seatDir, "config");
        var credDir = Path.Combine(configDir, "credentials");
        Directory.CreateDirectory(configDir);
        Directory.CreateDirectory(credDir);

        // Apollo uses relative paths for its assets and tools directories
        // (e.g. ./assets/shaders/ for GPU shaders). Create junction points so
        // Apollo can find these when running with workingDir = seatDir.
        var apolloRoot = Path.GetDirectoryName(_options.ApolloExePath)
                         ?? @"C:\Program Files\Apollo";
        CreateJunctionIfMissing(Path.Combine(seatDir, "assets"),
                                Path.Combine(apolloRoot, "assets"));
        CreateJunctionIfMissing(Path.Combine(seatDir, "tools"),
                                Path.Combine(apolloRoot, "tools"));

        // Seed TLS cert + key so Apollo doesn't need to generate (or fail to write) them.
        // All seats share the same server cert — Moonlight identifies seats by uniqueid, not cert.
        // Only seed if absent so reprovisions don't disturb active paired sessions.
        var apolloCreds = @"C:\Program Files\Apollo\config\credentials";
        foreach (var file in new[] { "cacert.pem", "cakey.pem" })
        {
            var dest = Path.Combine(credDir, file);
            var src  = Path.Combine(apolloCreds, file);
            if (!File.Exists(dest) && File.Exists(src))
            {
                try
                {
                    File.Copy(src, dest);
                    _logger.LogDebug("Seeded cert {File} to seat credentials dir", file);
                }
                catch (Exception ex)
                {
                    _logger.LogWarning(ex, "Could not seed cert {File} to {Dest}", file, dest);
                }
            }
        }
    }

    /// <summary>
    /// Copy apps.json from the Apollo install dir to the per-seat config/ dir.
    /// Apollo looks for apps in {workingDir}/config/apps.json. Without it the
    /// seat will have an empty app list. Always overwrites so the seat picks up
    /// any games the user adds to the main Apollo installation.
    /// </summary>
    private void EnsureSeatAppsJson(string seatDir)
    {
        var dest = Path.Combine(seatDir, "config", "apps.json");
        var source = @"C:\Program Files\Apollo\config\apps.json";

        if (!File.Exists(source))
        {
            _logger.LogDebug("Apollo apps.json not found at {Path} — seat will use built-in defaults", source);
            return;
        }

        try
        {
            File.Copy(source, dest, overwrite: true);
            _logger.LogDebug("Copied apps.json to seat config dir: {Dest}", dest);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Could not copy apps.json to {Dest}", dest);
        }
    }

    /// <summary>
    /// Ensure a per-seat sunshine_state.json exists with a unique server UUID.
    /// Apollo is pointed here via file_state = {seatDir}/config/sunshine_state.json in the config.
    /// Only creates the file if absent — preserves pairings on re-provision.
    /// </summary>
    private void EnsureSeatStateFile(string seatDir)
    {
        var statePath = Path.Combine(seatDir, "config", "sunshine_state.json");
        if (File.Exists(statePath)) return;

        // UUID format matches what Apollo writes: uppercase 8-4-4-4-12
        var uuid = Guid.NewGuid().ToString("D").ToUpperInvariant();
        var json = $$"""
            {
                "root": {
                    "named_devices": [],
                    "uniqueid": "{{uuid}}"
                }
            }
            """;

        File.WriteAllText(statePath, json, Encoding.UTF8);
        _logger.LogInformation("Created per-seat state file with UUID {Uuid}: {Path}", uuid, statePath);
    }

    /// <summary>
    /// Ensure the shared credentials file exists in the Apollo config root.
    /// If it doesn't exist yet, seed it from Apollo's default install location
    /// so the user doesn't have to set up credentials again from scratch.
    /// Apollo reads this file lazily on each web-UI/pairing request.
    /// </summary>
    private void EnsureSharedCredentials(string configDir)
    {
        var sharedCred = Path.Combine(configDir, "shared_credentials.json");
        if (File.Exists(sharedCred)) return;

        // Try to seed from Apollo's default credentials location
        var apolloDefault = @"C:\Program Files\Apollo\config\credentials.json";
        if (File.Exists(apolloDefault))
        {
            try
            {
                File.Copy(apolloDefault, sharedCred);
                _logger.LogInformation("Seeded shared credentials from Apollo default: {Path}", apolloDefault);
                return;
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Could not seed credentials from Apollo default");
            }
        }

        // Create a placeholder — user must visit the Apollo web UI (https://localhost:PORT) to set credentials
        _logger.LogWarning(
            "No shared credentials found at {Path}. " +
            "Visit the Apollo web UI after provisioning a seat to create credentials, " +
            "then the file will persist for future seats.",
            sharedCred);
    }

    /// <summary>
    /// Create a directory junction (mklink /J) at linkPath pointing to targetPath.
    /// Skips silently if the link already exists. Junction points work without
    /// SeCreateSymbolicLinkPrivilege so they work in SYSTEM context.
    /// </summary>
    private void CreateJunctionIfMissing(string linkPath, string targetPath)
    {
        if (Directory.Exists(linkPath)) return;

        if (!Directory.Exists(targetPath))
        {
            _logger.LogWarning("Junction target missing — skipping: {Target}", targetPath);
            return;
        }

        try
        {
            using var proc = Process.Start(new ProcessStartInfo("cmd.exe",
                $"/C mklink /J \"{linkPath}\" \"{targetPath}\"")
            {
                CreateNoWindow = true,
                UseShellExecute = false,
                RedirectStandardOutput = true,
                RedirectStandardError = true,
            })!;
            proc.WaitForExit(5000);
            if (proc.ExitCode != 0)
                _logger.LogWarning("mklink /J failed (exit {Code}) for {Link} -> {Target}",
                    proc.ExitCode, linkPath, targetPath);
            else
                _logger.LogDebug("Junction created: {Link} -> {Target}", linkPath, targetPath);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Could not create junction {Link} -> {Target}", linkPath, targetPath);
        }
    }

    /// <summary>
    /// Delete the config directory for a seat (on teardown).
    /// </summary>
    public void CleanupConfig(Guid seatId, string configDir)
    {
        var seatDir = Path.Combine(configDir, seatId.ToString("N"));
        if (Directory.Exists(seatDir))
        {
            try
            {
                Directory.Delete(seatDir, recursive: true);
                _logger.LogDebug("Cleaned up Apollo config dir: {Path}", seatDir);
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex,
                    "Failed to clean up Apollo config dir: {Path}", seatDir);
            }
        }
    }

    // ── NVENC preset tables ───────────────────────────────────────────────

    private static (int preset, string twopass, string spatialAq, int vbvIncrease)
        GetNvencSettings(NvencQualityPreset quality) => quality switch
    {
        NvencQualityPreset.Latency  => (1, "disabled",    "disabled", 0),
        NvencQualityPreset.Quality  => (7, "full_res",    "enabled",  40),
        _                           => (4, "quarter_res", "enabled",  20),  // Balanced
    };
}
